name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.1.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <6.7.0"
  build: ^2.4.1
  dart_style: ^2.3.6
  dartx: ^1.2.0
  glob: ^2.1.2
  isar: 3.1.0
  path: ^1.9.0
  source_gen: ^1.5.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^2.2.2
  matcher: ^0.12.16
  test: ^1.25.7
  very_good_analysis: ^5.1.0
